disabled_rules: # rule identifiers to exclude from running
  - todo
  - trailing_whitespace
  - vertical_whitespace
  - type_body_length
opt_in_rules: # some rules are only opt-in
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - discouraged_optional_collection
  - empty_string
  - file_name
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - yoda_condition
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

identifier_name:
  min_length: 2

line_length:
  warning: 120
  error: 200

function_body_length:
  warning: 50
  error: 200

file_length:
  warning: 400
  error: 800